---
- name: Configure Enterprise Service and Monitoring Tool
  hosts: all
  become: true
  vars_files:
    - config.yml

  tasks:
    - name: Install Apache (Debian)
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Debian"
      tags:
        - apache
      become: true

    - name: Install Apache (CentOS)
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"
      tags:
        - apache
      become: true

    - name: Install Node Exporter (Debian)
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.4>
        dest: /tmp/node_exporter.tar.gz
      when: ansible_distribution == 'Debian'
      tags:
        - monitoring

    - name: Install Node Exporter (CentOS)
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.4>
        dest: /tmp/node_exporter.tar.gz
      when: ansible_distribution == 'CentOS'
      tags:
        - monitoring

    - name: Extract Node Exporter on Debian
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
      when: ansible_distribution == 'Debian'
      tags:
        - monitoring
    
    - name: Extract Node Exporter on CentOS
      unarchive:
        src: /tmp/node_exporter.tar.gz 
        dest: /usr/local/bin/
        remote_src: yes
      when: ansible_distribution == 'CentOS'
      tags:
        - monitoring

    - name: Update MOTD
      lineinfile:
        path: /etc/motd
        line: "Ansible Managed by {{ motd_user }}"
        create: yes
      become: true
      tags:
        - motd
